[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  GMAIL_USER = "sim.agricultura.camaqua.rs@gmail.com"
  GMAIL_PASS = "zyctscuibqehkpgu"
  GMAIL_FROM_NAME = "SIM-CAMAQUA"

# Garante que, se você usar History PushState no futuro, as rotas não quebrem
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false